#!/bin/bash

if [ "$1" = "api" ]; then
    goctl api go -api mailgozero.api -dir . -style gozero
fi

if [ "$1" = "test" ]; then
    go run goqiozu.go -f etc/mailgozero-api.yaml
fi

if [ "$1" = "-deploy" ]; then
    ./mailgozero -f etc/mailgozero-api.yaml &
fi
