#!/bin/bash

if [ "$1" = "api" ]; then
    goctl api go -api mail_gozero.api -dir . -style gozero
fi

if [ "$1" = "test" ]; then
    go run goqiozu.go -f etc/mailgozero-api.yaml
fi

if [ "$1" = "-deploy" ]; then
    chmod 777 mailgozero
    ./mailgozero -f etc/mailgozero-api.yaml &
fi

if [ "$1" = "-build" ]; then   
   go build -o ./bin/mailgozero mailgozero.go 
fi