// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type RecMailReqeust struct {
	First       string `json:"first" validate:"required"`
	Last        string `json:"last" validate:"required"`
	Email       string `json:"email" validate:"required"`
	Phone       string `json:"phone"`
	CompanyName string `json:"companyName"`
	Detail      string `json:"detail"`
}

type RecMailResponse struct {
	Message string `json:"message"`
}
