// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-study/mail_gozero/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: Mail_gozeroHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mail/rec_mail_handler",
				Handler: MailHandler(serverCtx),
			},
		},
	)
}
